name: Day8
on:
  workflow_dispatch:
jobs:
  env_practice:
    name: env_practice
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "APP_NAME = GitHub Actions Learning" >> $GITHUB_ENV
          echo "VERSION = 1.0.0" >> $GITHUB_ENV
          echo "AUTHOR = Mukul" >>$GITHUB_ENV
      - name: step2
        run: |
          echo "Application: $APP_NAME"
          echo "Version: $VERSION"
          echo "Author: $AUTHOR"
      - name: step3
        run: |
          echo "RUN_ID=$GITHUB_RUN_ID" >>$GITHUB_ENV
      - name: step4
        run: |
          echo "Application: $APP_NAME"
          echo "Version: $VERSION"
          echo "Run id: $RUN_ID"

